---
title: "Tests de l'API piwik de data.gouv.fr"
output: html_notebook
---

```{r}
library(httr)
library(purrr)
library(tidyjson)
library(tidyverse)
```
```{r}
url <- "http://stats.data.gouv.fr/index.php?module=API"
request <- GET(url = url, 
               query = list(
                 method = "VisitsSummary.get",
                 idSite = 1,
                 period = "day",
                 date = "last365",
                 format = "json"))

content(request) %>% 
  map_df(~ map_df(., ~ .), .id = "date") %>% 
  mutate(bounce_rate = stringr::str_replace(bounce_rate, "%", "") %>% as.double())



visitsSummary <- function(idSite = 1, 
                          period = "day",
                          date = "last365",
                          url = "http://stats.data.gouv.fr/index.php?module=API") {
  request <- GET(url = url, 
               query = list(
                 method = "VisitsSummary.get",
                 idSite = idSite,
                 period = period,
                 date = date,
                 language = "fr",
                 format = "json"))
  content(request) %>% 
    map_df(~ map_df(., ~ .), .id = "date") %>% 
  mutate(bounce_rate = stringr::str_replace(bounce_rate, "%", "") %>% as.double()) %>% 
  mutate(date = lubridate::ymd(date))
}

adressesTroisAns <- visitsSummary(idSite = 13,
              period = "day",
              date = "last1000")

dataTroisAns <- visitsSummary(idSite = 1,
                              period = "day",
                              date = paste0("last", 365*3))

write_excel_csv(adressesTroisAns, path = "./data/adresse.data.gouv.fr/20150407_20170329_parjour_ensemble_site.csv")

write_excel_csv(dataTroisAns, path = "./data/data.gouv.fr/20140331_20170329_parjour_ensemble_site.csv")
```

```{r}
visitsSegmented <- function(idSite = 1,
                            period = "day",
                            date = "last365",
                            segment = "city==Marseille",
                            url = "http://stats.data.gouv.fr/index.php?module=API") {
  request <- GET(url = url, 
                 query = list(
                   method = "VisitsSummary.get",
                   idSite = idSite,
                   period = period,
                   date = date,
                   language = "fr",
                   segment = segment,
                   format = "json"))
  content(request) %>% 
    map_df(~ map_df(., ~ .), .id = "date") %>% 
    mutate(bounce_rate = stringr::str_replace(bounce_rate, "%", "") %>% as.double()) %>% 
    mutate(date = lubridate::ymd(date))
  
}

dataTroisAnsDownloads <- visitsSegmented(period = "day", date = paste0("last", 365*3),
                segment = "actionType==downloads")
write_excel_csv(dataTroisAnsDownloads, path = "./data/data.gouv.fr/20160926_20170329_parjour_downloads_site.csv")
```

```{r}
getPageUrls <- function(idSite = 1,
                        period = "day",
                        date = "last365",
                        url = "http://stats.data.gouv.fr/index.php?module=API") {
  request <- GET(url = url, 
                 query = list(
                   method = "Actions.getPageUrls",
                   idSite = idSite,
                   period = period,
                   date = date,
                   language = "fr",
                   filter_limit = -1,
                   format = "json"))
  content(request) %>% 
    map_df(~ map_df(., function(x) {
      data_frame(label = x$label,
                 nb_visits = x$nb_visits,
                 entry_nb_visits = ifelse(!is.null(x[["entry_nb_visits"]]),
                                           as.integer(x[["entry_nb_visits"]]),
                                           0),
                 exit_nb_visits = ifelse(!is.null(x[["exit_nb_visits"]]),
                                         as.integer(x[["exit_nb_visits"]]),
                                         0))
    }), .id = "date") %>% 
    mutate(date = lubridate::ymd(date))
}

urls <- getPageUrls(date = paste0("last", 365*3))

write_excel_csv(urls, "./data/data.gouv.fr/20140331_20170329_parjour_parurl.csv")
```

```{r}
getDownloads <- function(idSite = 1,
                         period = "day",
                         date = "last100",
                         url = "http://stats.data.gouv.fr/index.php?module=API") {
  request <- GET(url = url, 
                 query = list(
                   method = "Actions.getDownloads",
                   idSite = idSite,
                   period = period,
                   date = date,
                   expanded = 1,
                   flat = 1,
                   filter_limit = -1,
                   format = "json"))
  content(request) %>% 
    map_df(~ map_df(., function(x) {
      data_frame(label = x$label,
                 nb_visits = x$nb_visits,
                 entry_nb_visits = ifelse(!is.null(x[["entry_nb_visits"]]),
                                          as.integer(x[["entry_nb_visits"]]),
                                          0),
                 exit_nb_visits = ifelse(!is.null(x[["exit_nb_visits"]]),
                                         as.integer(x[["exit_nb_visits"]]),
                                         0))
    }), .id = "date") %>% 
    mutate(date = lubridate::ymd(date))
}

downloads100jours <- getDownloads()
downloadsavant <- getDownloads(date = "2016-09-01,2016-12-20")
downloadsencoreavant <- getDownloads(date = "2016-06-01,2016-08-31")
downloadsavant1 <- getDownloads(date = "2016-01-01,2016-05-31")
downloadsavant2 <- getDownloads(date = "2015-09-01,2015-12-31")
downloadsavant3 <- getDownloads(date = "2015-06-01,2015-08-31")
downloadsavant4 <- getDownloads(date = "2015-01-01,2015-05-31")
downloadsavant5 <- getDownloads(date = "2014-09-01,2014-12-31")
downloadsavant6 <- getDownloads(date = "2014-06-01,2014-08-31")
downloadsavant7 <- getDownloads(date = "2014-01-01,2014-05-31")

downloads <- bind_rows(downloadsavant7, downloadsavant6, downloadsavant5, downloadsavant4, downloadsavant3, downloadsavant2, downloadsavant1, downloadsencoreavant, downloadsavant, downloads100jours)

write_excel_csv(downloads, "./data/data.gouv.fr/20140101_20170329_parjour_downloads_urls.csv")
```

```{r}
getOutlinks <- function(idSite = 1,
                        period = "day",
                        date = "last30",
                        url = "http://stats.data.gouv.fr/index.php?module=API") {
  request <- GET(url = url, 
                 query = list(
                   method = "Actions.getOutlinks",
                   idSite = idSite,
                   period = period,
                   date = date,
                   expanded = 1,
                   flat = 1,
                   filter_limit = -1,
                   format = "json"))
  content(request) %>% 
    map_df(~ map_df(., function(x) {
      data_frame(label = x$label,
                 nb_visits = x$nb_visits,
                 exit_nb_visits = ifelse(!is.null(x[["exit_nb_visits"]]),
                                         as.integer(x[["exit_nb_visits"]]),
                                         0))
    }), .id = "date") %>% 
    mutate(date = lubridate::ymd(date))
}



outlinks <- map_df(0:26, ~ getOutlinks(date = paste0(ymd(20150101) + months(.), ",", ymd(20150101) + months(. + 1) - days(1))))

write_excel_csv(outlinks, "./data/data.gouv.fr/20150101_20170329_parjour_outlinks_urls.csv")
```

```{r}
getSiteSearchKeywords <- function(idSite = 1,
                                  period = "day",
                                  date = "last30",
                                  url = "http://stats.data.gouv.fr/index.php?module=API") {
  request <- GET(url = url, 
                 query = list(
                   method = "Actions.getSiteSearchKeywords",
                   idSite = idSite,
                   period = period,
                   date = date,
                   filter_limit = -1,
                   format = "json"))
  content(request) %>% 
    map_df(~ map_df(., function(x) {
      data_frame(label = x$label,
                 nb_visits = x$nb_visits,
                 exit_nb_visits = ifelse(!is.null(x[["exit_nb_visits"]]),
                                         as.integer(x[["exit_nb_visits"]]),
                                         0),
                 nb_pages_per_search = x$nb_pages_per_search,
                 bounce_rate = x$bounce_rate,
                 exit_rate = x$exit_rate)
    }), .id = "date") %>% 
      mutate(bounce_rate = stringr::str_replace(bounce_rate, "%", "") %>% as.double()) %>%
      mutate(exit_rate = stringr::str_replace(exit_rate, "%", "") %>% as.double()) %>%
      mutate(date = lubridate::ymd(date))
}
  
keywords <- map_df(0:38, ~ getSiteSearchKeywords(date = paste0(ymd(20140101) + months(.), ",", ymd(20140101) + months(. + 1) - days(1))))

write_excel_csv(keywords, "./data/data.gouv.fr/20140101_20170329_parjour_keywords_keywords.csv")
```

